### ISSUE TITLE
table "file_meta" already exists

### ISSUE THREAD

**Issue by nichtsen** [c4pt0r/ff#1]
bootstrap() will CREATE TABLE `file_meta` every time when server starts even if the table already exist (for example ,when the server restart or build index for exiting ff.db with flag -build-index)

I got this error:

    (/home/go/src/github.com/c4pt0r/ff/ff.go:115)
    [2020-02-21 08:27:51]  table "file_meta" already exists

[ff.go#L115l](https://github.com/c4pt0r/ff/blob/master/ff.go#L115l)

**Comment by c4pt0r** [comment]
Thank you, already fixed in the latest commit. But thank you for you PR anyway
